version: "3.8"

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config/named.conf:/etc/bind/named.conf:ro
      - ./config/named.conf.options:/etc/bind/named.conf.options:ro
      - ./config/named.conf.local:/etc/bind/named.conf.local:ro
      - ./config/db.forward.osWDo.local:/etc/bind/db.forward.osWDo.local:ro
      - ./config/db.reverse.1.168.192:/etc/bind/db.reverse.1.168.192:ro
      - ./config/managed-keys.bind:/etc/bind/managed-keys.bind:ro
      - ./config/managed-keys.bind.jnl:/etc/bind/managed-keys.bind.jnl:ro
      - bind_cache:/var/cache/bind
    networks:
      bindnet:
        ipv4_address: 192.168.12.11
    cap_add:
      - NET_BIND_SERVICE
    dns:
      - 127.0.0.1
    environment:
      - TZ=Europe/Zurich

networks:
  bindnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24

volumes:
  bind_cache:
